### ISSUE TITLE
Crashing while start using short link

### ISSUE THREAD

**Issue by RogeryRY** [fork-maintainers/iceraven-browser#641]
After update to 2.8.1 crashed when using short link "New tab"
MIUI 14.0.3
Android 12

**Comment by akliuxingyuan** [comment]
what's reproduce steps, crash only when launch from shortcut?

**Comment by MikalaiFuture** [comment]
https://github.com/fork-maintainers/iceraven-browser/assets/31849614/69421e3f-1783-4072-a554-653910459739

**Comment by akliuxingyuan** [comment]
It's a coldstart? may be related to #642, can you provide error logs via adb
```sh
adb logcat -e io.github.forkmaintainers.iceraven "*:E"
```

**Comment by liyafe1997** [comment]
> It's a coldstart? may be related to #642, can you provide error logs via adb
> 
> ```shell
> adb logcat -e io.github.forkmaintainers.iceraven "*:E"
> ```

For the Iceraven itself, it was not crashed. Below down is the logcat when I run Iceraven:

```
adb logcat -e io.github.forkmaintainers.iceraven "*:E"
--------- beginning of main
08-07 17:51:57.211  3289  3455 E DollieAdapterService: notifyActivityState pkg:io.github.forkmaintainers.iceraven/io.github.forkmaintainers.iceraven.App state:2 fg:true mUid:10217
08-07 17:51:57.223  3289  3455 E DollieAdapterService: notifyActivityState pkg:io.github.forkmaintainers.iceraven/io.github.forkmaintainers.iceraven.App state:8 fg:false mUid:10217
08-07 17:52:08.681  1679  3383 E ActivityTaskManager: ensureVisibilityAndConfig begin next:ActivityRecord{7d82631 u0 io.github.forkmaintainers.iceraven/.App t18}
08-07 17:52:08.682  1679  3383 E ActivityTaskManager: ensureVisibilityAndConfig starting:ActivityRecord{7d82631 u0 io.github.forkmaintainers.iceraven/.App t18}, kept:true
08-07 17:52:08.682  1679  3383 E ActivityTaskManager: ensureVisibilityAndConfig end next:ActivityRecord{7d82631 u0 io.github.forkmaintainers.iceraven/.App t18}
08-07 17:52:08.711  3289  3455 E DollieAdapterService: notifyActivityState pkg:io.github.forkmaintainers.iceraven/io.github.forkmaintainers.iceraven.App state:2 fg:true mUid:10217
```

The crash is happen in systemui, if I catch the systemui's log:

```
adb logcat -e com.android.systemui "*:E"
--------- beginning of crash
08-07 17:53:44.608 20561 20620 E AndroidRuntime: FATAL EXCEPTION: wmshell.splashworker
08-07 17:53:44.608 20561 20620 E AndroidRuntime: Process: com.android.systemui, PID: 20561
08-07 17:53:44.608 20561 20620 E AndroidRuntime: java.lang.IllegalStateException: Target with the name "a1_t" cannot be found in the VectorDrawable to be animated.
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.prepareLocalAnimator(AnimatedVectorDrawable.java:863)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.graphics.drawable.AnimatedVectorDrawable$AnimatedVectorDrawableState.prepareLocalAnimators(AnimatedVectorDrawable.java:841)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.graphics.drawable.AnimatedVectorDrawable.ensureAnimatorSet(AnimatedVectorDrawable.java:954)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.graphics.drawable.AnimatedVectorDrawable.start(AnimatedVectorDrawable.java:938)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at com.android.wm.shell.startingsurface.SplashscreenIconDrawableFactory$AnimatableIconAnimateListener$1.onAnimationStart(SplashscreenIconDrawableFactory.java:285)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.animation.Animator$AnimatorListener.onAnimationStart(Animator.java:539)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:1031)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.animation.ValueAnimator.startAnimation(ValueAnimator.java:1280)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.animation.ValueAnimator.start(ValueAnimator.java:1082)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.animation.ValueAnimator.start(ValueAnimator.java:1106)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at com.android.wm.shell.startingsurface.SplashscreenIconDrawableFactory$AnimatableIconAnimateListener.ensureAnimationStarted(SplashscreenIconDrawableFactory.java:329)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at com.android.wm.shell.startingsurface.SplashscreenIconDrawableFactory$AnimatableIconAnimateListener.draw(SplashscreenIconDrawableFactory.java:336)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.View.getDrawableRenderNode(View.java:23767)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.View.drawBackground(View.java:23688)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.View.draw(View.java:23462)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.View.updateDisplayListIfDirty(View.java:22304)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:549)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:555)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:641)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.ViewRootImpl.draw(ViewRootImpl.java:5718)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5441)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4418)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2877)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10700)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:1165)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:1054)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1417)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:966)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:110)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:205)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:293)
08-07 17:53:44.608 20561 20620 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
--------- beginning of system
08-07 17:53:44.663  1679  2830 E LockoutResetTracker: Removing dead callback for: com.android.systemui
08-07 17:53:44.938  3289  3455 E Booster_NetworkQoeMonitor: [callBackRegisterStateChanged]Register success: com.android.systemui
--------- beginning of main
08-07 17:53:44.938  3289  3455 E NetworkQualityPredict: Register success: com.android.systemui
```

Seems the crash is related to animation.

Also, I found if I open iceraven from some where else (E.g. a link in SMS), the SystemUI will not crash. But if I open it from the launcher, the SystemUI will crash.
